/** Durable transport-only SubmissionOperation ledger. Persist PREPARED before provider actuation. */
export type SubmissionOperationKind = "GO" | "BOOTSTRAP" | "REVIEW_DISPATCH" | "SEDIMENT" | "DELIVER_CHILD_RESULT";
export type SubmissionOperationState = "PREPARED" | "DISPATCHING" | "OBSERVED_ACCEPTED" | "COMPLETED" | "UNCERTAIN" | "FAILED_SAFE" | "CANCELLED";
export interface SubmissionBaseline { conversationRef?: string; routeRef: string; assistantMessageCount: number; userMessageCount: number; lastUserMessageFingerprint?: string; lastAssistantMessageFingerprint?: string; headFingerprint?: string; observedAt: number; }
export interface SubmissionObservation extends Omit<SubmissionBaseline, "observedAt"> { observedAt?: number; generationActive?: boolean; }
export interface SubmissionOperation { operationId: string; operationKind: SubmissionOperationKind; workItemId: string; logicalThreadId: string; targetCarrierRef: string; providerConversationRef?: string; payloadFingerprint: string; payload?: string; parentEpoch?: number; preSubmitBaseline: SubmissionBaseline; state: SubmissionOperationState; createdAt: number; lastObservedAt: number; dispatchClaimedAt?: number; resultingTurnRef?: string; error?: string; }
export interface SubmissionOperationStore { get(key: string): Promise<unknown>; set(value: Record<string, unknown>): Promise<void>; }
export const SUBMISSION_OPERATIONS_KEY = "noosSubmissionOperations";
const terminalStates = new Set<SubmissionOperationState>(["COMPLETED", "FAILED_SAFE", "CANCELLED"]);
const executionOwningStates = new Set<SubmissionOperationState>(["DISPATCHING", "UNCERTAIN", "OBSERVED_ACCEPTED"]);

export class SubmissionOperationLedger {
  private queue: Promise<void> = Promise.resolve();
  constructor(private readonly store: SubmissionOperationStore) {}
  async list(): Promise<SubmissionOperation[]> { const value = await this.store.get(SUBMISSION_OPERATIONS_KEY); const records = value && typeof value === "object" ? (value as Record<string, unknown>)[SUBMISSION_OPERATIONS_KEY] : undefined; return Array.isArray(records) ? records.filter(isSubmissionOperation).map(cloneOperation) : []; }
  async get(operationId: string): Promise<SubmissionOperation | undefined> { return (await this.list()).find(item => item.operationId === operationId); }
  async prepare(input: Omit<SubmissionOperation, "operationId" | "state" | "createdAt" | "lastObservedAt"> & { operationId?: string; now?: number }): Promise<SubmissionOperation> {
    return this.serialized(async () => { const records = await this.list(); const operationId = input.operationId ?? createOperationId(); const existing = records.find(item => item.operationId === operationId); if (existing) { if (existing.payloadFingerprint !== input.payloadFingerprint || existing.targetCarrierRef !== input.targetCarrierRef) throw new Error(`operation_id_reuse_conflict:${operationId}`); return existing; } const now = input.now ?? Date.now(); const operation: SubmissionOperation = { operationId, operationKind: input.operationKind, workItemId: input.workItemId, logicalThreadId: input.logicalThreadId, targetCarrierRef: input.targetCarrierRef, providerConversationRef: input.providerConversationRef, payloadFingerprint: input.payloadFingerprint, payload: input.payload, parentEpoch: input.parentEpoch, preSubmitBaseline: { ...input.preSubmitBaseline }, state: "PREPARED", createdAt: now, lastObservedAt: now }; await this.save([...records, operation]); return cloneOperation(operation); });
  }
  /** Persisted claim; concurrent calls in this process are serialized and only one wins. */
  async claim(operationId: string, now = Date.now()): Promise<SubmissionOperation | undefined> {
    return this.serialized(async () => { const records = await this.list(); const operation = records.find(item => item.operationId === operationId); if (!operation) return undefined; if (operation.state === "DISPATCHING") return operation; if (operation.state !== "PREPARED") return operation; const active = records.find(item => item.operationId !== operationId && item.targetCarrierRef === operation.targetCarrierRef && executionOwningStates.has(item.state)); if (active) return undefined; operation.state = "DISPATCHING"; operation.dispatchClaimedAt = now; operation.lastObservedAt = now; await this.save(records); return cloneOperation(operation); });
  }
  async record(operationId: string, state: SubmissionOperationState, details: { now?: number; error?: string; resultingTurnRef?: string } = {}): Promise<SubmissionOperation | undefined> {
    return this.serialized(async () => { const records = await this.list(); const operation = records.find(item => item.operationId === operationId); if (!operation || !isAllowedTransition(operation.state, state)) return operation && cloneOperation(operation); operation.state = state; operation.lastObservedAt = details.now ?? Date.now(); if (details.error !== undefined) operation.error = details.error; if (details.resultingTurnRef !== undefined) operation.resultingTurnRef = details.resultingTurnRef; await this.save(records); return cloneOperation(operation); });
  }
  /** Re-arm only after explicit proven-not-accepted evidence and a fresh baseline. */
  async rearm(operationId: string, baseline: SubmissionBaseline, now = Date.now()): Promise<SubmissionOperation | undefined> {
    return this.serialized(async () => { const records = await this.list(); const operation = records.find(item => item.operationId === operationId); if (!operation || (operation.state !== "FAILED_SAFE" && operation.state !== "UNCERTAIN")) return operation && cloneOperation(operation); operation.preSubmitBaseline = { ...baseline }; operation.state = "PREPARED"; operation.lastObservedAt = now; operation.error = undefined; await this.save(records); return cloneOperation(operation); });
  }
  async reconcile(operationId: string, observation: SubmissionObservation): Promise<{ outcome: "PROVEN_ACCEPTED" | "PROVEN_NOT_ACCEPTED" | "STILL_AMBIGUOUS"; operation?: SubmissionOperation }> {
    return this.serialized(async () => { const records = await this.list(); const operation = records.find(item => item.operationId === operationId); if (!operation) return { outcome: "STILL_AMBIGUOUS" as const }; const baseline = operation.preSubmitBaseline; const sameConversation = !operation.providerConversationRef || !observation.conversationRef || operation.providerConversationRef === observation.conversationRef; const sameRoute = observation.routeRef === baseline.routeRef; const changed = fingerprintsChanged(observation, baseline); const accepted = sameConversation && sameRoute && (observation.userMessageCount > baseline.userMessageCount || observation.assistantMessageCount > baseline.assistantMessageCount || changed); const unchanged = sameConversation && sameRoute && observation.userMessageCount === baseline.userMessageCount && observation.assistantMessageCount === baseline.assistantMessageCount && !changed; operation.lastObservedAt = observation.observedAt ?? Date.now(); if (accepted) { operation.state = "OBSERVED_ACCEPTED"; await this.save(records); return { outcome: "PROVEN_ACCEPTED" as const, operation: cloneOperation(operation) }; } if (unchanged && !observation.generationActive) { operation.state = "FAILED_SAFE"; await this.save(records); return { outcome: "PROVEN_NOT_ACCEPTED" as const, operation: cloneOperation(operation) }; } operation.state = "UNCERTAIN"; await this.save(records); return { outcome: "STILL_AMBIGUOUS" as const, operation: cloneOperation(operation) }; });
  }
  private async save(records: SubmissionOperation[]): Promise<void> { await this.store.set({ [SUBMISSION_OPERATIONS_KEY]: records }); }
  private async serialized<T>(work: () => Promise<T>): Promise<T> { const previous = this.queue; let release!: () => void; this.queue = new Promise(resolve => { release = resolve; }); await previous; try { return await work(); } finally { release(); } }
}
export function createChromeSubmissionStore(chromeStorage: { get(key: string): Promise<unknown>; set(value: Record<string, unknown>): Promise<void> }): SubmissionOperationStore { return { get: key => chromeStorage.get(key), set: value => chromeStorage.set(value) }; }
function fingerprintsChanged(observation: SubmissionObservation, baseline: SubmissionBaseline): boolean { return (observation.headFingerprint !== undefined && observation.headFingerprint !== baseline.headFingerprint) || (observation.lastUserMessageFingerprint !== undefined && observation.lastUserMessageFingerprint !== baseline.lastUserMessageFingerprint) || (observation.lastAssistantMessageFingerprint !== undefined && observation.lastAssistantMessageFingerprint !== baseline.lastAssistantMessageFingerprint); }
function isAllowedTransition(from: SubmissionOperationState, to: SubmissionOperationState): boolean { if (from === to) return true; if (terminalStates.has(from)) return false; if (from === "PREPARED") return to === "CANCELLED"; if (from === "DISPATCHING") return ["OBSERVED_ACCEPTED", "UNCERTAIN", "FAILED_SAFE", "CANCELLED"].includes(to); if (from === "OBSERVED_ACCEPTED") return ["COMPLETED", "UNCERTAIN"].includes(to); if (from === "UNCERTAIN") return ["OBSERVED_ACCEPTED", "FAILED_SAFE", "CANCELLED"].includes(to); return false; }
function isSubmissionOperation(value: unknown): value is SubmissionOperation { if (!value || typeof value !== "object") return false; const item = value as Partial<SubmissionOperation>; return typeof item.operationId === "string" && typeof item.targetCarrierRef === "string" && typeof item.payloadFingerprint === "string" && typeof item.state === "string" && Boolean(item.preSubmitBaseline && typeof item.preSubmitBaseline === "object"); }
function cloneOperation(operation: SubmissionOperation): SubmissionOperation { return { ...operation, preSubmitBaseline: { ...operation.preSubmitBaseline } }; }
function createOperationId(): string { return globalThis.crypto?.randomUUID?.() ?? `op-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`; }
